### ISSUE TITLE
Add buckets API

### ISSUE THREAD

**Issue by nicovak** [influxdata/influxdb-client-ruby#66]
__Proposal:__
Implement buckets API for create and delete routes

__Current behavior:__
Actually we can't create or delete a bucket with the ruby client.

__Desired behavior:__
Implement some routes of [influxdb 2 api docs](https://docs.influxdata.com/influxdb/v2.0/api/#tag/Buckets) bucket API
- Create
- Delete
- List

__Use case:__
Delete or create a bucket is vital if you want to delete all data in a single shot or make the creation of bucket dynamic.

**Comment by bednar** [comment]
Hi @nicovak,

thanks for using our client.

We will take a look and try prepare management API for next release. Stay tuned.

Regards

**Comment by bednar** [comment]
@nicovak, the issue is fixed in [Milestone 1.12.0](https://github.com/influxdata/influxdb-client-ruby/milestone/13). You could use a preview version of Management API by:

```console
gem install influxdb-client-apis --version 1.12.0.pre.1937
```

Here is an example how to create `Bucket`: 
https://github.com/influxdata/influxdb-client-ruby/blob/master/examples/create_new_bucket.rb
